QCon12/Controllers/HomeController.cs
#region

using System.Web.Mvc;

#endregion

namespace QCon12.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

QCon12/Controllers/PalestraController.cs
using System;
using System.Data;
using System.Web.Mvc;
using QCon12.Models;

namespace QCon12.Controllers
{
    public class PalestraController : Controller
    {
        private readonly QCon12Context db = QCon12Context.Instance;

        public ActionResult Index()
        {
            return View(db.Palestras.Include("Palestrante").Include("Track"));
        }

        public ActionResult Details(int id = 0)
        {
            var palestra = db.Palestras.Find(id);
            if (palestra == null)
                return HttpNotFound();
            return View(palestra);
        }

        public ActionResult Create()
        {
            LoadPalestrantesAndTracksToViewBag();
            return View(new Palestra {Horario = new DateTime(2012, 8, 4)});
        }

        private void LoadPalestrantesAndTracksToViewBag(Palestrante palestrante = null, Track track = null)
        {
            ViewBag.Palestrantes = new SelectList(db.Palestrantes, "Id", "Nome", palestrante);
            ViewBag.Tracks = new SelectList(db.Tracks, "Id", "Nome", track);
        }

        [HttpPost]
        public ActionResult Create(Palestra palestra)
        {
            if (ModelState.IsValid)
            {
                db.Palestras.Add(palestra);
                return RedirectToAction("Index");
            }
            LoadPalestrantesAndTracksToViewBag();
            return View(palestra);
        }

        public ActionResult Edit(int id = 0)
        {
            var palestra = db.Palestras.Find(id);
            if (palestra == null)
                return HttpNotFound();
            LoadPalestrantesAndTracksToViewBag(palestra.Palestrante, palestra.Track);
            return View(palestra);
        }

        [HttpPost]
        public ActionResult Edit(Palestra palestra)
        {
            if (ModelState.IsValid)
            {
                var entry = db.Entry(palestra);
                entry.State = EntityState.Modified;
                return RedirectToAction("Index");
            }
            LoadPalestrantesAndTracksToViewBag();
            return View(palestra);
        }

        public ActionResult Delete(int id = 0)
        {
            var palestra = db.Palestras.Find(id);
            if (palestra == null)
                return HttpNotFound();
            return View(palestra);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var palestra = db.Palestras.Find(id);
            db.Palestras.Remove(palestra);
            return RedirectToAction("Index");
        }
    }
}

QCon12/Controllers/TrackController.cs
using System.Data;
using System.Web.Mvc;
using QCon12.Models;

namespace QCon12.Controllers
{
    public class TrackController : Controller
    {
        private readonly QCon12Context db = QCon12Context.Instance;

        public ActionResult Index()
        {
            return View(db.Tracks);
        }

        public ActionResult Details(int id = 0)
        {
            var track = db.Tracks.Find(id);
            if (track == null)
                return HttpNotFound();
            return View(track);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Track track)
        {
            if (ModelState.IsValid)
            {
                db.Tracks.Add(track);
                return RedirectToAction("Index");
            }

            return View(track);
        }

        public ActionResult Edit(int id = 0)
        {
            var track = db.Tracks.Find(id);
            if (track == null)
                return HttpNotFound();
            return View(track);
        }

        [HttpPost]
        public ActionResult Edit(Track track)
        {
            if (ModelState.IsValid)
            {
                db.Entry(track).State = EntityState.Modified;
                return RedirectToAction("Index");
            }
            return View(track);
        }

        public ActionResult Delete(int id = 0)
        {
            var track = db.Tracks.Find(id);
            if (track == null)
                return HttpNotFound();
            return View(track);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var track = db.Tracks.Find(id);
            db.Tracks.Remove(track);
            return RedirectToAction("Index");
        }
    }
}

QCon12/Views/Home/Index.cshtml
<header>
    <div class="content-wrapper">
        <div class="float-left">
            <p class="site-title">
                <a href="~/">ASP.NET Web API</a></p>
        </div>
    </div>
</header>
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>
                    Welcome to ASP.NET Web API!</h1>
                <h2>
                    Modify the code in this template to jump-start your ASP.NET Web API development.</h2>
            </hgroup>
            <p>
                ASP.NET Web API allows you to expose your applications, data and services to the
                web directly over HTTP.
            </p>
            <p>
                To learn more about ASP.NET Web API visit <a href="http://go.microsoft.com/fwlink/?LinkID=238195"
                    title="ASP.NET Web API Website">http://asp.net/web-api</a>. The page features
                <mark>videos, tutorials, and samples</mark> to help you get the
                most from ASP.NET Web API. If you have any questions about ASP.NET Web API, visit
                <a href="http://go.microsoft.com/fwlink/?LinkID=238196" title="ASP.NET Web API Forum">
                    our forums</a>.
            </p>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        <h3>
            We suggest the following steps:</h3>
        <ol class="round">
            <li>@Html.ActionLink("Palestrantes", "Index", "Palestrante")</li>
            <li>@Html.ActionLink("Tracks", "Index", "Track")</li>
            <li>@Html.ActionLink("Palestras", "Index", "Palestra")</li>
        </ol>
    </section>
</div>